GRPC localhost:50051/kadepay.v1.services.wallet.WalletService/GetWalletId
Content-Type: application/json

{
  "x_pub_key": "tpubD6NzVbkrYhZ4Xnn2kkAVyM2rtmWCM3oH2z8GWbJTmTbM3XJnMf3JQpam7uzZpyBETfqfFet5dXb1dZLNPp7oQ5zKxpgc56QQzrg6GbsQp3z"
}