###
GRPC localhost:50051/kadepay.v1.services.invoice.InvoiceService/CreateInvoice
Content-Type: application/json

{
  "network": "Bitcoin",
  "currency": "₿",
  "amount": "4",
  "description": "Test invoice creation on Bitcoin"
}