###
GRPC localhost:50051/kadepay.v1.services.invoice.InvoiceService/CreateInvoice
Content-Type: application/json

{
  "pub_key_id": "4110d117-ef71-4b51-afb9-078810634bea",
  "network": "Bitcoin",
  "currency_code": "BTC",
  "amount": "4",
  "description": "Test invoice creation on Bitcoin"
}