name: build.yml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    needs:
      - tests
      - check-format

    runs-on: ubuntu-latest
    environment: Development

    steps:
      - uses: actions/checkout@v6
      - name: Build
        run: cargo build

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Tests
        run: cargo test

  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Check code style
        run: cargo fmt --check
